import type { LN2Tank, CanisterRack, CryoBox, CellVial, ThawAuditRecord } from '../types/inventory';

export const INITIAL_TANKS: LN2Tank[] = [
  {
    id: 'TANK-01',
    name: 'Lab Main LN2 CryoTank (MVE 6-Rack)',
    location: '동결보존실 (Room 304 - BioBank Suite)',
    temperature: -196.0,
    ln2LevelPercentage: 92,
    lastRefilled: '2026-09-22',
    totalCapacityVials: 4860, // 6 racks * 10 boxes * 81 wells
    status: 'Normal',
  },
];

export const INITIAL_RACKS: CanisterRack[] = [
  { id: 'RACK-1', tankId: 'TANK-01', name: 'Rack 1', description: '암세포주 및 형질전환주', totalBoxes: 10 },
  { id: 'RACK-2', tankId: 'TANK-01', name: 'Rack 2', description: '면역 & 혈액 세포주', totalBoxes: 10 },
  { id: 'RACK-3', tankId: 'TANK-01', name: 'Rack 3', description: '줄기세포 & 초대배양 Primary', totalBoxes: 10 },
  { id: 'RACK-4', tankId: 'TANK-01', name: 'Rack 4', description: '바이러스 패키징 & 생산세포주', totalBoxes: 10 },
  { id: 'RACK-5', tankId: 'TANK-01', name: 'Rack 5', description: 'CRISPR 유전자 교정주', totalBoxes: 10 },
  { id: 'RACK-6', tankId: 'TANK-01', name: 'Rack 6', description: '워킹 스톡 & 마스터 스톡 백업', totalBoxes: 10 },
];

const BOX_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'] as const;

export const INITIAL_BOXES: CryoBox[] = [1, 2, 3, 4, 5, 6].flatMap((rackNum) => {
  return BOX_LETTERS.map((letter, idx) => {
    const boxId = `${rackNum}-${letter}`;
    const tier = idx + 1;
    let colorTag = '#3b82f6';
    if (rackNum === 1) colorTag = '#3b82f6'; // blue
    else if (rackNum === 2) colorTag = '#10b981'; // emerald
    else if (rackNum === 3) colorTag = '#8b5cf6'; // purple
    else if (rackNum === 4) colorTag = '#f59e0b'; // amber
    else if (rackNum === 5) colorTag = '#ec4899'; // pink
    else colorTag = '#06b6d4'; // cyan

    return {
      id: boxId,
      name: `Box ${boxId}`,
      tankId: 'TANK-01',
      rackId: `RACK-${rackNum}`,
      dimension: 9 as const, // 9x9 (81 wells)
      colorTag,
      description: `Rack ${rackNum} - Box ${boxId}`,
    };
  });
});

export const INITIAL_VIALS: CellVial[] = [
  {
    id: 'VIAL-2026-001',
    cellLineName: 'HEK293T',
    cellType: 'Human',
    passage: 12,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-A',
    row: 'A',
    col: 1,
    freezeDate: '2026-08-15',
    vialsStored: 4,
    cultureMedium: 'DMEM (High Glucose) + 10% FBS + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    geneModification: 'SV40 Large T-Ag',
    researcher: 'Dr. Sungil Jang',
    notes: 'Master stock. Thaws rapidly at 37C water bath. DMEM + 10% FBS.',
    status: 'Stored',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'VIAL-2026-002',
    cellLineName: 'HEK293T',
    cellType: 'Human',
    passage: 12,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-A',
    row: 'A',
    col: 2,
    freezeDate: '2026-08-15',
    vialsStored: 4,
    cultureMedium: 'DMEM (High Glucose) + 10% FBS + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Dr. Sungil Jang',
    status: 'Stored',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'VIAL-2026-003',
    cellLineName: 'HEK293T',
    cellType: 'Human',
    passage: 12,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-A',
    row: 'A',
    col: 3,
    freezeDate: '2026-08-15',
    vialsStored: 4,
    cultureMedium: 'DMEM (High Glucose) + 10% FBS + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Dr. Sungil Jang',
    status: 'Stored',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'VIAL-2026-004',
    cellLineName: 'HeLa CCL-2',
    cellType: 'Human',
    passage: 19,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-A',
    row: 'B',
    col: 1,
    freezeDate: '2026-07-20',
    vialsStored: 3,
    cultureMedium: 'EMEM + 10% FBS + 1% NEAA + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    geneModification: 'Cervical carcinoma WT',
    researcher: 'Yuna Choi',
    notes: 'Fast growing epithelial morphology.',
    status: 'Stored',
    updatedAt: '2026-08-10T11:20:00Z',
  },
  {
    id: 'VIAL-2026-005',
    cellLineName: 'HeLa CCL-2',
    cellType: 'Human',
    passage: 19,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-A',
    row: 'B',
    col: 2,
    freezeDate: '2026-07-20',
    vialsStored: 3,
    cultureMedium: 'EMEM + 10% FBS + 1% NEAA + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Yuna Choi',
    status: 'Stored',
    updatedAt: '2026-08-10T11:20:00Z',
  },
  {
    id: 'VIAL-2026-011',
    cellLineName: 'A549',
    cellType: 'Human',
    passage: 14,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-B',
    row: 'B',
    col: 3,
    freezeDate: '2026-07-05',
    vialsStored: 3,
    cultureMedium: 'F-12K + 10% FBS + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    geneModification: 'KRAS G12S',
    researcher: 'Minwoo Park',
    status: 'Stored',
    updatedAt: '2026-07-06T10:00:00Z',
  },
  {
    id: 'VIAL-2026-013',
    cellLineName: 'MC38 (Colon)',
    cellType: 'Mouse',
    passage: 12,
    tankId: 'TANK-01',
    rackId: 'RACK-1',
    boxId: '1-B',
    row: 'D',
    col: 6,
    freezeDate: '2026-06-30',
    vialsStored: 2,
    cultureMedium: 'DMEM + 10% FBS + 1% P/S + 1% Sodium Pyruvate',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Yuna Choi',
    notes: 'Syngeneic C57BL/6 model. Caution: subculture at 70-80% confluence.',
    status: 'Stored',
    updatedAt: '2026-07-01T15:00:00Z',
  },
  {
    id: 'VIAL-2026-006',
    cellLineName: 'Jurkat Clone E6-1',
    cellType: 'Human',
    passage: 8,
    tankId: 'TANK-01',
    rackId: 'RACK-2',
    boxId: '2-A',
    row: 'A',
    col: 1,
    freezeDate: '2026-08-28',
    vialsStored: 5,
    cultureMedium: 'RPMI-1640 + 10% FBS + 1% HEPES + 1% P/S',
    freezingMedium: 'CryoStor CS10',
    geneModification: 'CD19-CAR knock-in candidate',
    researcher: 'Minwoo Park',
    notes: 'RPMI 1640 + 10% FBS + 1% Pen/Strep. Suspension culture.',
    status: 'Stored',
    updatedAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'VIAL-2026-007',
    cellLineName: 'Jurkat Clone E6-1',
    cellType: 'Human',
    passage: 8,
    tankId: 'TANK-01',
    rackId: 'RACK-2',
    boxId: '2-A',
    row: 'A',
    col: 2,
    freezeDate: '2026-08-28',
    vialsStored: 5,
    cultureMedium: 'RPMI-1640 + 10% FBS + 1% HEPES + 1% P/S',
    freezingMedium: 'CryoStor CS10',
    researcher: 'Minwoo Park',
    status: 'Stored',
    updatedAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'VIAL-2026-008',
    cellLineName: 'THP-1',
    cellType: 'Human',
    passage: 6,
    tankId: 'TANK-01',
    rackId: 'RACK-2',
    boxId: '2-B',
    row: 'C',
    col: 4,
    freezeDate: '2026-08-10',
    vialsStored: 2,
    cultureMedium: 'RPMI-1640 + 10% FBS + 0.05 mM 2-mercaptoethanol',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Yuna Choi',
    notes: 'Monocyte differentiation assay ready (PMA responsive). Low stock!',
    status: 'Stored',
    updatedAt: '2026-08-11T09:15:00Z',
  },
  {
    id: 'VIAL-2026-009',
    cellLineName: 'RAW 264.7',
    cellType: 'Mouse',
    passage: 11,
    tankId: 'TANK-01',
    rackId: 'RACK-2',
    boxId: '2-C',
    row: 'E',
    col: 5,
    freezeDate: '2026-06-12',
    vialsStored: 4,
    cultureMedium: 'DMEM + 10% FBS + 1% P/S',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Dr. Sungil Jang',
    notes: 'Scrape gently or use cell scraper, do not over-trypsinize.',
    status: 'Stored',
    updatedAt: '2026-06-15T16:00:00Z',
  },
  {
    id: 'VIAL-2026-010',
    cellLineName: 'iPSC-CL03',
    cellType: 'Stem Cell',
    passage: 5,
    tankId: 'TANK-01',
    rackId: 'RACK-3',
    boxId: '3-A',
    row: 'A',
    col: 1,
    freezeDate: '2026-09-02',
    vialsStored: 6,
    cultureMedium: 'mTeSR Plus Feeder-Free Media',
    freezingMedium: 'mTeSR Plus + 10% DMSO + 10 uM Y-27632',
    geneModification: 'OCT4/SOX2/KLF4/c-MYC reprogrammed',
    researcher: 'Dr. Sungil Jang',
    notes: 'Matrigel coating required. Add 10 uM Rock inhibitor (Y-27632) for first 24h after thaw.',
    status: 'Stored',
    updatedAt: '2026-09-03T18:00:00Z',
  },
  {
    id: 'VIAL-2026-012',
    cellLineName: '293FT High Titer',
    cellType: 'Human',
    passage: 10,
    tankId: 'TANK-01',
    rackId: 'RACK-4',
    boxId: '4-A',
    row: 'A',
    col: 1,
    freezeDate: '2026-08-01',
    vialsStored: 8,
    cultureMedium: 'DMEM + 10% FBS + 0.1 mM NEAA + 1 mM Sodium Pyruvate + 500 ug/mL G418',
    freezingMedium: '90% FBS + 10% DMSO',
    researcher: 'Dr. Sungil Jang',
    notes: 'Optimal for lentivirus packaging with pMD2.G and psPAX2.',
    status: 'Stored',
    updatedAt: '2026-08-02T12:00:00Z',
  },
  {
    id: 'VIAL-2026-014',
    cellLineName: 'CHO-K1',
    cellType: 'Other',
    passage: 15,
    tankId: 'TANK-01',
    rackId: 'RACK-6',
    boxId: '6-A',
    row: 'A',
    col: 1,
    freezeDate: '2026-09-10',
    vialsStored: 5,
    cultureMedium: 'F-12K Nutrient Mixture + 10% FBS',
    freezingMedium: 'F-12K + 10% FBS + 10% DMSO',
    researcher: 'Minwoo Park',
    status: 'Stored',
    updatedAt: '2026-09-11T08:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: ThawAuditRecord[] = [
  {
    id: 'THAW-LOG-001',
    vialId: 'VIAL-2026-001',
    cellLineName: 'HEK293T',
    locationString: 'TANK-01 > RACK-A > BOX-01 > 4번 슬롯',
    thawedBy: 'Minwoo Park',
    thawedDate: '2026-09-20 10:15',
    purpose: 'Viral vector co-transfection experiment (Batch #4)',
    vialsRemaining: 4,
    notes: 'High viability observed (~96%) after 24h attachment.',
  },
  {
    id: 'THAW-LOG-002',
    vialId: 'VIAL-2026-006',
    cellLineName: 'Jurkat Clone E6-1',
    locationString: 'TANK-01 > RACK-B > BOX-03 > 3번 슬롯',
    thawedBy: 'Dr. Sungil Jang',
    thawedDate: '2026-09-15 14:00',
    purpose: 'T-cell activation and cytokine secretion assay',
    vialsRemaining: 5,
    notes: 'Seeded in 24-well plate with CD3/CD28 dynabeads.',
  },
];
